# 1：单变量线性回归
### **by:MLZZY**
**实验描述：根据城市人口数量，预测开小吃店的利润。
ex1data1.txt：第一列是城市人口数量，第二列是该城市小吃店利润。**

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
A=np.eye(5)
A

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [3]:
path="/home/mw/input/andrew_ml_ex14179/ex1data1.txt"
data=pd.read_csv(path,header=None,names=['Population','Profit'])
data.head()

Population   Profit
0      6.1101  17.5920
1      5.5277   9.1302
2      8.5186  13.6620
3      7.0032  11.8540
4      5.8598   6.8233

In [4]:
data.plot(kind='scatter',x='Population',y='Profit',figsize=(12,8))
plt.show()

<Figure size 864x576 with 1 Axes>

In [5]:
#计算J(Ѳ)——损失函数，X为矩阵
def computeCost(X,y,theta):
    inner=np.power(((X*theta.T)-y),2)
    return np.sum(inner)/(2*len(X))

In [6]:
#加上Ones列，Ones列的值恒为1,即表示theta0的系数恒为1
data.insert(0,'Ones',1)
#初始化X和y
cols=data.shape[1]
X=data.iloc[:,:-1]
y=data.iloc[:,cols-1:cols]

In [7]:
X.head()

Ones  Population
0     1      6.1101
1     1      5.5277
2     1      8.5186
3     1      7.0032
4     1      5.8598

In [8]:
y.head()

Profit
0  17.5920
1   9.1302
2  13.6620
3  11.8540
4   6.8233

In [9]:
X=np.matrix(X.values)
y=np.matrix(y.values)
theta=np.matrix(np.array([0,0]))

In [10]:
X.shape,theta.T.shape,y.shape

((97, 2), (2, 1), (97, 1))

In [11]:
#计算损失函数的值
computeCost(X,y,theta)

32.072733877455676

In [12]:
#梯度下降法对theta进行更新
def gradientDescent(X,y,theta,alpha,iters):
    temp=np.matrix(np.zeros(theta.shape))
    parameters=int(theta.ravel().shape[1])
    cost=np.zeros(iters)
    for i in range(iters):
        error=(X*theta.T)-y
        #注意tenta的同步更新（视频中强调的）
        for j in range(parameters):
            term=np.multiply(error,X[:,j])
            temp[0,j]=theta[0,j]-((alpha/len(X))*np.sum(term))
        theta=temp
        cost[i]=computeCost(X,y,theta)
    return theta,cost

In [13]:
#学习率
alpha=0.01
#迭代次数
iters=1500

In [14]:
g, cost = gradientDescent(X, y, theta, alpha, iters)
g

matrix([[-3.63029144,  1.16636235]])

In [15]:
cost

array([6.73719046, 5.93159357, 5.90115471, ..., 4.48343473, 4.48341145,
       4.48338826])

In [16]:
predict1=[1,3.5]*g.T
print("predict1:",predict1)
predict2=[1,7]*g.T
print("predict2",predict2)

predict1: [[0.45197679]]
predict2 [[4.53424501]]


In [19]:
# numpy.linspace(start, stop, num=50, endpoint=True, retstep=False,dtype=None)产生从start到stop的等差数列，num为元素个数，默认50个
x = np.linspace(data.Population.min(),data.Population.max(),100)
f=g[0,0]+(g[0,1]*x)
fig,ax=plt.subplots(figsize=(12,8))
ax.plot(x,f,'r',label='Prediction')
ax.scatter(data.Population,data.Profit,label='Traing Data')
ax.legend(loc=2)
ax.set_xlabel('Population')
ax.set_ylabel('Profit')
ax.set_title('Predicted Profit vs. Population Size')
plt.show()

<Figure size 864x576 with 1 Axes>