# 2：多变量线性回归及正规方程
### **by:MLZZY**
**实验描述：根据已有数据，建立模型，预测房屋的售价
ex1data2.txt：第一列是房屋大小，第二列是卧室数量，第三列是房屋售价。**


In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
path='/home/mw/input/andrew_ml_ex14179/ex1data2.txt'
data2=pd.read_csv(path,header=None,names=['Size','Bedrooms','Price'])
data2.head()

Size  Bedrooms   Price
0  2104         3  399900
1  1600         3  329900
2  2400         3  369000
3  1416         2  232000
4  3000         4  539900

In [5]:
#观察数据发现size变量是bedrooms变量的1000倍，特征归一化后，统一量级会让梯度下降收敛的更快
#将每类特征减去其平均值后除以其标准差
data2=(data2-data2.mean())/data2.std()
data2.head()

Size  Bedrooms     Price
0  0.130010 -0.223675  0.475747
1 -0.504190 -0.223675 -0.084074
2  0.502476 -0.223675  0.228626
3 -0.735723 -1.537767 -0.867025
4  1.257476  1.090417  1.595389

In [4]:
#计算J(Ѳ)——损失函数，X为矩阵
def computeCost(X,y,theta):
    inner=np.power(((X*theta.T)-y),2)
    return np.sum(inner)/(2*len(X))

In [5]:
def gradientDescent(X, y, theta, alpha, iters):
    temp = np.matrix(np.zeros(theta.shape))
    parameters = int(theta.ravel().shape[1])
    cost = np.zeros(iters)
    for i in range(iters):
        error = (X * theta.T) - y
        for j in range(parameters):
            term = np.multiply(error, X[:,j])
            temp[0,j] = theta[0,j] - ((alpha / len(X)) * np.sum(term))
        theta = temp
        cost[i] = computeCost(X, y, theta)       
    return theta, cost

In [6]:
#常规操作：加一列全为1的常数项
data2.insert(0,'Ones',1)

In [7]:
#初始化x和y
cols=data2.shape[1]
x2=data2.iloc[:,0:cols-1]
y2=data2.iloc[:,cols-1:cols]
alpha=0.01
iters=1500
#转换成matrix格式，初始化theta
x2=np.matrix(x2.values)
y2=np.matrix(y2.values)
theta2=np.matrix(np.array([0,0,0]))
x2.shape,y2.shape,theta2.T.shape

((47, 3), (47, 1), (3, 1))

In [8]:
#运行梯度下降算法
g2,cost2=gradientDescent(x2,y2,theta2,alpha,iters)
g2,cost2

(matrix([[-1.10585300e-16,  8.84042349e-01, -5.24551809e-02]]),
 array([0.4805491 , 0.47198588, 0.46366462, ..., 0.13068671, 0.13068671,
        0.13068671]))

**正规方程**

In [9]:
def normalEqn(x,y):
    #x.T@x等价于x.T.dot(x)
    theta=np.linalg.inv(x.T@x)@x.T@y
    return theta

In [10]:
final_theta2=normalEqn(x2,y2)
final_theta2

matrix([[-1.11022302e-16],
        [ 8.84765988e-01],
        [-5.31788197e-02]])